# Site
name: "Tip Season"
title: "Tip Season - Tech & Interview Tips"
description: "Tip Season - Tech & Coding Interview Tips and Tricks"
#logo: 'assets/images/logo1.png'
#favicon: 'assets/images/logo.png'
logo: assets/images/TipSeasonLogo.jpeg
baseurl: ''
google_analytics: 'G-KBVC6R6HS5'
disqus: 'tipseason'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
mailchimp-enable: false
include: ["_pages"]
url: https://tipseason.com
permalink: /:title/
assetsUrl: https://assets.tipseason.com
imagesUrl: https://assets.tipseason.com/images

# Authors
authors:
  Pramod:
    name: Mani
    display_name: Mani
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: manigopalmurthy at gmail dot com
    web: https://www.instagram.com/thetipseason/
    twitter: https://twitter.com/thetipseason
    url: https://twitter.com/thetipseason
    description: "Educating everyone with the beauty of programming!!"

  Mani:
    name: Mani
    display_name: Mani
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: manigopalmurthy at gmail dot com
    web: https://www.instagram.com/thetipseason/
    twitter: https://twitter.com/thetipseason
    url: https://twitter.com/thetipseason
    description: "Educating everyone with the beauty of programming!!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: ./page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, 'src', 'out']

collections:
  # aitools:
  #   output: true
  #   permalink: /ai-tool/:path
  aicategories:
    output: true
    permalink: /ai-tools/category/:path
  tips:
    output: true
    permalink: /tips/:path
  interviews:
    output: true
    permalink: /interviews/:path